#!/usr/bin/env ruby

require 'rubygems'
require 'mongo'

def run s
  puts s
  puts `#{s}`
end

db = Mongo::Connection.new.db 'nodeknockout'
db_teams = db.collection 'Team'
db_people = db.collection 'Person'

apps = `heroku list`.split("\n").map { |app| app.split(/\s+/).first }

db_teams.find().each do |t|
  app = 'nko-' + t['slug'].gsub('_', '-')[0,26]
  next if apps.include?(app)

  # create app
  run "heroku create --stack beech #{app}"

  # post deploy hook
  run "heroku addons:add custom_domains:basic --app #{app}"
  run "heroku addons:add deployhooks:http url=http://nodeknockout.com/deploys --app #{app}"

  # add everyone on the team
  run "heroku sharing:add all@nodeknockout.com --app #{app}"
  people = t['members'].map { |p| db_people.find_one p['_id'] }
  people.each do |p|
    #run "heroku sharing:add #{p['email']} --app #{app}"
  end

  # transfer ownership
  #run "heroku sharing:transfer #{people.first['email']} --app #{app}"
  run "heroku sharing:transfer all@nodeknockout.com --app #{app}"
  puts "\n"
end
