#!/usr/bin/env ruby
# ruby script/add-confirm-keys > tmp/confirm-keys.txt

require 'rubygems'
require 'active_support'
require 'fastercsv'
require 'mongo'

# db = Mongo::Connection.new("localhost", 27017).db("mydb")
# db.authenticate(my_user_name, my_password)

db = Mongo::Connection.new.db "nodeknockout"
@people = db.collection 'Person'

@people.find( :confirmed => false ).each do |person|
  puts [person['email'], person['_id'], person['confirmKey']].to_csv
end
