#!/usr/bin/env ruby

require 'rubygems'
require 'mongo'
require 'json'

puts `curl -X POST http://localhost:8000/scores/refresh`

db = Mongo::Connection.new.db "nodeknockout"
@db_teams = db.collection 'Team'
@db_people = db.collection 'Person'

@winners = {}

def green s
  "<b>#{s}</b>"
end

def red s
  "<del>#{s}</del>"
end

def output t, dimension, score
  out = @winners.values.include?(t)
  s = "[#{t['application']}](#{t['url']}) by [#{t['name']}](http://nodeknockout.com/teams/#{t['slug']}) - #{sprintf('%.2f', score)}"
  s = if !@winners[dimension] && !out
      @winners[dimension] = t
      green s
    elsif out
      red s
    else
      s
    end
  puts "1. #{s}"
end

puts "\n\#\#\# Overall"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.overall', -1]], :limit => 5}).each do |t|
  output t, 'overall', t['score']['overall'] / 5
end

puts "\n\#\#\# Solo"
@db_teams.find({ :validDeploy => true, :members => {'$size' => 1} }, { :sort => [['score.overall', -1]], :limit => 5}).each do |t|
  output t, 'solo', t['score']['overall'] / 5
end

puts "\n\#\#\# Utility"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.final.utility', -1]], :limit => 5}).each do |t|
  output t, 'utility', t['score']['final']['utility']
end

puts "\n\#\#\# Design"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.final.design', -1]], :limit => 5}).each do |t|
  output t, 'design', t['score']['final']['design']
end

puts "\n\#\#\# Innovation"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.final.innovation', -1]], :limit => 5}).each do |t|
  output t, 'innovation', t['score']['final']['innovation']
end

puts "\n\#\#\# Completeness"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.final.completeness', -1]], :limit => 5}).each do |t|
  output t, 'completeness', t['score']['final']['completeness']
end

puts "\n\#\#\# Popularity"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.final.popularity', -1]], :limit => 5}).each do |t|
  output t, 'popularity', t['score']['final']['popularity']
end
