#!/usr/bin/env ruby

require 'rubygems'
require 'mongo'
require 'json'

#puts `curl -X POST http://localhost:8000/scores/refresh`

db = Mongo::Connection.new.db "nodeknockout"
@db_teams = db.collection 'Team'
@db_people = db.collection 'Person'

@winners = {}

def green s
  puts "\033[32m#{s}\033[0m"
end

def red s
  puts "\033[31m#{s}\033[0m"
end

def output t, dimension, score
  out = @winners.values.include?(t)
  s = "  #{t['application']} by #{t['name']} - #{score}"
  if !@winners[dimension] && !out
    @winners[dimension] = t
    green s
  elsif out
    red s
  else
    puts s
  end
end

puts "\nOVERALL"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.overall', -1]], :limit => 5}).each do |t|
  output t, 'overall', t['score']['overall']
end

puts "\nSOLO"
@db_teams.find({ :validDeploy => true, :members => {'$size' => 1} }, { :sort => [['score.overall', -1]], :limit => 5}).each do |t|
  output t, 'solo', t['score']['overall']
end

puts "\nUTILITY"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.final.utility', -1]], :limit => 5}).each do |t|
  output t, 'utility', t['score']['final']['utility']
end

puts "\nDESIGN"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.final.design', -1]], :limit => 5}).each do |t|
  output t, 'design', t['score']['final']['design']
end

puts "\nINNOVATION"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.final.innovation', -1]], :limit => 5}).each do |t|
  output t, 'innovation', t['score']['final']['innovation']
end

puts "\nCOMPLETENESS"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.final.completeness', -1]], :limit => 5}).each do |t|
  output t, 'completeness', t['score']['final']['completeness']
end

puts "\nPOPULARITY"
@db_teams.find({ :validDeploy => true }, { :sort => [['score.final.popularity', -1]], :limit => 5}).each do |t|
  output t, 'popularity', t['score']['final']['popularity']
end

@winners.values.each do |t|
  puts t['name']
  t['members'].each do |p|
    p = @db_people.find({ :_id => p['_id'] }).first
    puts "  #{p['name']} <#{p['email']}>"
  end
end
